package com.tessera.fleet.ingestion;

import java.util.ArrayList;
import java.util.List;

import com.tessera.fleet.dataset.FleetDataset;
import com.tessera.fleet.model.PositionReport;

/**
 * Replays a pre-generated {@link FleetDataset} in wall-clock time (SRS §2.6).
 *
 * <p>This is <em>simulated</em> position data and is disclosed as such (FR-7.2) —
 * but unlike a naive live simulator it is physically plausible: the dataset was
 * generated by driving shortest-path tours along a real OpenStreetMap road
 * network under acceleration, cornering and speed-limit constraints, so
 * positions move continuously and never jump. See
 * {@link com.tessera.fleet.dataset.FleetDatasetGenerator}.
 *
 * <p>The track loops. Every vehicle starts and ends parked at its depot, so the
 * seam is continuous.
 */
public class DatasetPositionSource implements PositionSource {

    private final FleetDataset dataset;
    private final long startedEpochMs;
    private int lastTick = -1;

    public DatasetPositionSource(FleetDataset dataset) {
        this(dataset, System.currentTimeMillis());
    }

    /** Test/support constructor: pin the replay clock origin. */
    public DatasetPositionSource(FleetDataset dataset, long startedEpochMs) {
        this.dataset = dataset;
        this.startedEpochMs = startedEpochMs;
    }

    @Override
    public String id() {
        return "dataset";
    }

    @Override
    public String displayName() {
        return "Generated fleet trajectories — " + dataset.area();
    }

    @Override
    public boolean isSubstitute() {
        return true;
    }

    @Override
    public String disclosure() {
        return "Positions are SIMULATED, not real. They are replayed from a "
                + "pre-generated dataset in which synthetic vehicles drive "
                + "shortest-path rounds along a real OpenStreetMap road network "
                + "for " + dataset.area() + ", under real per-road speed limits and "
                + "physical acceleration, braking and cornering limits — so the "
                + "motion is plausible, but no physical vehicles or telematics feed "
                + "are involved. The " + fmtMinutes() + " track repeats on a loop.";
    }

    private String fmtMinutes() {
        long seconds = dataset.tickCount() * dataset.tickMillis() / 1000L;
        long minutes = Math.max(1, seconds / 60);
        return minutes + "-minute";
    }

    /** The dataset tick that corresponds to a wall-clock instant. */
    int tickAt(long epochMillis) {
        long elapsed = Math.max(0, epochMillis - startedEpochMs);
        long tick = elapsed / dataset.tickMillis();
        return (int) Math.floorMod(tick, dataset.tickCount());
    }

    @Override
    public List<PositionReport> poll() {
        long now = System.currentTimeMillis();
        int tick = tickAt(now);
        if (tick == lastTick) {
            return List.of(); // the track has not advanced yet
        }
        lastTick = tick;
        return frame(tick, now);
    }

    /** Package-private for tests: the reports for one dataset tick. */
    List<PositionReport> frame(int tick, long epochMillis) {
        List<PositionReport> out = new ArrayList<>(dataset.vehicleCount());
        for (int v = 0; v < dataset.vehicleCount(); v++) {
            out.add(new PositionReport(
                    dataset.vehicleId(v),
                    dataset.driverName(v),
                    dataset.latitude(tick, v),
                    dataset.longitude(tick, v),
                    dataset.headingDeg(tick, v),
                    dataset.speedKph(tick, v),
                    epochMillis));
        }
        return out;
    }

    public int vehicleCount() {
        return dataset.vehicleCount();
    }
}
